### ISSUE TITLE
Moshi JsonAdapter issue

### ISSUE THREAD

**Issue by gkaradagan** [Guardsquare/appsweep-gradle#2]
Hi, 
When I try to run  ':app:uploadToAppSweepBetaDebug' task, I get an error below
* What went wrong:
Execution failed for task ':app:uploadToAppSweepBetaDebug'.
> 'com.squareup.moshi.Moshi$Builder com.squareup.moshi.Moshi$Builder.addLast(com.squareup.moshi.JsonAdapter$Factory)'

**Comment by titze** [comment]
Hi @gkaradagan,

is this the full stacktrace you are seeing?

Is the project available somewhere so that we can try to recreate the problem locally?

Best regards,
Dennis

**Comment by titze** [comment]
Thanks! We identified the bug, and are working on a fix.

**Comment by titze** [comment]
Hi @gkaradagan,

what we thought was the root cause of the problem turned out to be a dead end.

As of now, we are not able to reproduce the problem on our end. Could you share the project here, or with me directly?

**Comment by gkaradagan** [comment]
@titze Sorry, I can not share the project with anyone :( We installed the application manually on the website, it is currently solving our problem. We follow the new updates of the library.

**Comment by titze** [comment]
@gkaradagan is it possible to share some information, or none at all?

To maybe reproduce this, we would be interested in the `build.gradle` files.
If this is not possible, could you tell us:
- if you are using other Gradle plugins, and which?
- if you are doing anything manually in the gradle files that forces versions on dependencies?

**Comment by gkaradagan** [comment]
Hi @titze,

We are using these plugins; 

apply plugin: 'org.jetbrains.changelog'
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'com.google.firebase.appdistribution'
apply plugin: 'com.apollographql.apollo'
apply plugin: 'com.google.firebase.crashlytics'
apply from: 'ci.gradle'
apply from: 'localization.gradle'
apply from: "../gradle/ktlint.gradle"
apply from: "../gradle/detekt.gradle"

I hope that this helps you to find out the bug

**Comment by titze** [comment]
Hi @gkaradagan, sorry for the late reply.
We did several updates in the meanwhile, would it be possible to try again with the latest version?

**Comment by gkaradagan** [comment]
Hi @titze ,

Unfortunately, It gives the same error :) The problem may occur because of our gradle file. We need to refactor it. Then I will write again.
